#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
# Install Nginx
sudo apt update
sudo apt install nginx -y

# Add the custom header to the default Nginx server configuration
sudo sed -i '/server_name _;/a \  add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Test the configuration and reload Nginx
sudo nginx -t
sudo systemctl reload nginx
