#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
# Install HAProxy
sudo apt update
sudo apt install haproxy -y

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg <<EOF
global
    maxconn 5000
    daemon

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 415569-web-01 54.236.26.10:80 check
    server 415569-web-02 34.203.33.43:80 check
EOF

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl start haprox
